### ISSUE TITLE
Recompiles everytime instead of checking if anything changed

### ISSUE THREAD

**Issue by tobykurien** [oehme/xtend-gradle-plugin#20]
While the java compiler, etc. checks for changes since last compile and skips if there aren't any, the Xtend compiler seems to always re-compile all xtend source files, leading to much longer build times when using gradle compared to Eclipse.

**Comment by oehme** [comment]
Incremental builds work in all my projects. Please provide a project to reproduce.

**Comment by tobykurien** [comment]
If I run ```gradle assembleDebug```, then run it again after it completes, I still see all the Xtend compiler warnings as it compiles the xtend sources again. Does this not happen in your case?

**Comment by oehme** [comment]
It works with the android skeleton app you posted on the newsgroup. If it
happens for another project, I need to see that project or at least the
build file.
Am 11.01.2015 09:53 schrieb "Toby Kurien" <notifications@github.com>:

**Comment by oehme** [comment]
Ah sorry, after a clean build I seen the problem, too. The BuildConfig is generated after Xtend, but should be generated before. I'll look into that.
