### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by ltennstedt** [oehme/xtend-gradle-plugin#36]
The plugin shows often the following warnings at runtime:

Warning: NLS unused message: line_separator_platform_mac_os_9 in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: auth_alreadySpecified in: org.eclipse.core.internal.runtime.messages
Warning: NLS missing message: plugin_unableToGetActivator in: org.eclipse.core.internal.runtime.messages

plugin version 1.0.18
Gradle 4.0.2
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OS: Arch Linux

**Comment by oehme** [comment]
Can you please provide a small example project that shows this issue? I don't get it on my projects.

**Comment by cdietrich** [comment]
@oehme i see this e.g. in the logs of xtext-web
http://services.typefox.io/open-source/jenkins/job/xtext-web/job/cd_gradle41/2/console

**Comment by cdietrich** [comment]
needed to kill the gradle daemon to see the message locally.
i assume this is caused by the plugin and xtext using different eclipse.core.runtime versions.
the plugin still uses 3.7

https://github.com/xtext/xtext-gradle-plugin/blob/bc93df7791dedb029c3303799012a28741cf1d01/xtext-gradle-plugin/build.gradle

whilst xtext uses 3.12

https://github.com/eclipse/xtext-core/blob/master/gradle/versions.gradle
https://github.com/eclipse/xtext-core/blob/6133b66961261d8b2102aa74099b93418dbce0bf/org.eclipse.xtext/build.gradle

also the groupId changes `org.eclipse.platform:org.eclipse.core.runtime`

**Comment by oehme** [comment]
The plugin only uses core.runtime to write property files. It [doesn't leak](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/tasks/internal/IncrementalXtextBuilderProvider.xtend#L50) it into the actual compiler process. So there you will have only what Xtext uses.

**Comment by cdietrich** [comment]
why do i have to kill the daemon to get the message then?

**Comment by cdietrich** [comment]
@oehme if i inc the versions for jdt and runtime i dont get the error anymore

**Comment by oehme** [comment]
Is JDT under a different namespace as well now? That would explain problems, since then you'd end up with both JDT artifacts on the classpath.

**Comment by cdietrich** [comment]
actually not. but i don't know how options/transtive dependencies are collected in gradle.
e.g. if i use gradle dependencies the plugins dont show up

**Comment by cdietrich** [comment]
can i somehow show the path the plugin is executed with?

**Comment by oehme** [comment]
Ah, I think I know why - it probably looks up a resource on the classpath and our [filtering classloader](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/tasks/internal/FilteringClassLoader.xtend) doesn't override `getResource()`. It should, to provide proper isolation between the Gradle plugin and Xtext.

**Comment by cdietrich** [comment]
indeed

**Comment by ltennstedt** [comment]
Example project, but I do not think that this issue is related to a specific project setup:

https://github.com/togliu/finnmath

**Comment by oehme** [comment]
The fix will be available as version 1.0.19 shortly (it's building right now).

**Comment by ltennstedt** [comment]
Thanks for the really quick response and for the fix!

https://github.com/togliu/finnmath/blob/master/build.gradle

No warnings anymore!
